# 回帰モデルのbaseline
split: 
  split_type: shuffle
  valid_size: 0.2
  test_size: 0.2
features:
model:
  model_name: lightgbm_regressor
  params:
    boosting_type: gbdt
    objective: regression
    metric: rmse
    num_leaves: 31
    learning_rate: 0.1
    n_estimators: 100000
    random_state: 0
post_process:
mlflow: True
experiment_name: lightgbm_comparison
run_name: regressor_baseline # 要変更
model_save_path: model