split: 
  split_type: shuffle
  valid_size: 0.2
  test_size: 0.2
features:
  - group
model:
  model_name: lightgbm_regressor
  params:
    boosting_type: gbdt
    objective: regression
    metric: mse
    num_leaves: 16
    learning_rate: 0.1
    n_estimators: 100000
    random_state: 0
mlflow: True
run_name: 20230903_lightgbm_mse # 要変更
model_save_path: model
csv_save_path: ../../results/20230831_lightgbm_mse.csv # 要変更