split: 
  split_type: shuffle
  valid_size: 0.2
  test_size: 0.2
features:
  - group
model:
  model_name: lightgbm_regressor
  params:
    boosting_type: gbdt
    objective: regression
    metric: mse
    num_leaves: 16
    learning_rate: 0.1
    n_estimators: 100000
    random_state: 0
post_process:
  process_type: number
  params:
    upper: 
      limit: 10
      value: 3
    lower: 
      limit: 10
      value: -2
mlflow: False
run_name: 20230903_lightgbm_mse # 要変更
model_save_path: model
eval_csv_save_path: ../../results/20230903_lightgbm_mse_eval.csv # 要変更
test_csv_save_path: ../../results/20230903_lightgbm_mse_test.csv # 要変更